// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package bootstrap

import (
	"github.com/kerwinan/kwina-demo/client"
	"github.com/kerwinan/kwina-demo/option"
	"github.com/kerwinan/kwina-demo/provider"
	"github.com/kerwinan/kwina-demo/service"
)

// Injectors from wire.go:

func setupProvider() (*provider.Provider, error) {
	options, err := option.NewOptions()
	if err != nil {
		return nil, err
	}
	clientClient, err := client.NewClient(options)
	if err != nil {
		return nil, err
	}
	serviceService, err := service.NewService(options, clientClient)
	if err != nil {
		return nil, err
	}
	providerProvider, err := provider.NewProvider(options, serviceService, clientClient)
	if err != nil {
		return nil, err
	}
	return providerProvider, nil
}
